-- MySQL Script generated by MySQL Workbench
-- 10/31/15 17:33:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema landingem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema landingem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `landingem` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `landingem` ;

-- -----------------------------------------------------
-- Table `landingem`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `landingem`.`categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`idCategoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landingem`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `landingem`.`productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `precio` FLOAT NOT NULL COMMENT '',
  `stock` INT NULL COMMENT '',
  `oferta` FLOAT NULL COMMENT '',
  `imagen` VARCHAR(255) NULL COMMENT '',
  `categorias_idCategorias` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProducto`)  COMMENT '',
  INDEX `fk_productos_categorias1_idx` (`categorias_idCategorias` ASC)  COMMENT '',
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categorias_idCategorias`)
    REFERENCES `landingem`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landingem`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `landingem`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landingem`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `landingem`.`clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `dreccion` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(30) NULL COMMENT '',
  PRIMARY KEY (`idCliente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landingem`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `landingem`.`facturas` (
  `idfacturas` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fechapedido` DATETIME NULL COMMENT '',
  `clientes_idCliente` INT NOT NULL COMMENT '',
  `total` FLOAT NULL COMMENT '',
  PRIMARY KEY (`idfacturas`)  COMMENT '',
  INDEX `fk_facturas_clientes_idx` (`clientes_idCliente` ASC)  COMMENT '',
  CONSTRAINT `fk_facturas_clientes`
    FOREIGN KEY (`clientes_idCliente`)
    REFERENCES `landingem`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landingem`.`detallefactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `landingem`.`detallefactura` (
  `idDetalleFactura` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `facturas_idfacturas` INT NOT NULL COMMENT '',
  `productos_idProducto` INT NOT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  INDEX `fk_detallefactura_facturas1_idx` (`facturas_idfacturas` ASC)  COMMENT '',
  INDEX `fk_detallefactura_productos1_idx` (`productos_idProducto` ASC)  COMMENT '',
  PRIMARY KEY (`idDetalleFactura`)  COMMENT '',
  CONSTRAINT `fk_detallefactura_facturas1`
    FOREIGN KEY (`facturas_idfacturas`)
    REFERENCES `landingem`.`facturas` (`idfacturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallefactura_productos1`
    FOREIGN KEY (`productos_idProducto`)
    REFERENCES `landingem`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
