-- MySQL Script generated by MySQL Workbench
-- 10/25/15 03:05:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema landingem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema landingem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `landingem` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `landingem` ;

-- -----------------------------------------------------
-- Table `landingem`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `landingem`.`productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `precio` FLOAT NOT NULL COMMENT '',
  `stock` INT NULL COMMENT '',
  `oferta` FLOAT NULL COMMENT '',
  PRIMARY KEY (`idProducto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `landingem`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `landingem`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `rol` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
